### PR TITLE
Python2 and Python3 compatible

### PR DESCRIPTION
**Pull request by ghost**
I made the script compatible with python2 and python3.

This is a merged version of https://github.com/hnsl/unox/pull/12.

### CODE REVIEW

**Comment by ghost** [comment]
@hnsl Any ideas on this one? 😃

**Comment by ghost** [comment]
I found a bug with files in subfolders.

**Comment by hnsl** [comment]
Thank you for your contribution! I wish I actually had tests. Unfortunately I stopped using this myself and I don't have time to write them.

**Comment by mechanical-fish** [comment]
Thank you @cfpettersson for fixing this bug -- I just found and fixed it myself, and now I am spared the trouble of submitting a PR. :)

**Pull request merged**
