### PR TITLE
Downgraded to Python2

### PR DESCRIPTION
**Pull request by uglygus**
OS X default install is python 2.7 only. Saves having to install python3

### CODE REVIEW

**Comment by hnsl** [comment]
Why not just `brew install python3`?

**Comment by uglygus** [comment]
Ideally unox should have as large a user base as possible though and 2.7 is still unfortunately more prevalent. It's certainly possible to install python 3 but since I personally don't need it for anything else I'd rather avoid it if I can. I hope also to run this on several machines. The more standard the install the better.  

I see now that my pull request is not clear enough lines 28-37 can be cut and replaced with 'import fsevents'. If you will consider a pull request for this I'll close this one and make a cleaner one.

**Comment by hnsl** [comment]
Yeah, I think it's a better idea to put the fsevents install information in the README instead to keep the code clean. Can you change that and remove the extra space on line 88?

**Comment by hnsl** [comment]
I believe you don't have to close this pull request, you can just update your branch and github will update the pull request.

**Pull request merged**
